apiVersion: v1
kind: Service
metadata:
  name: apigateway-server-svc
spec:
  type: LoadBalancer
  selector:
    app: apigateway-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
