apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-server
  labels:
    app: apigateway-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apigateway-server
  template:
    metadata:
      labels:
        app: apigateway-server
    spec:
      containers:
        - name: apigateway-server
          image: sendebojyoti/apigateway-server:0.0.2
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
